default:
  image: mcr.microsoft.com/dotnet/sdk:3.1

cache:
  paths:
    - $HOME/.npm/

stages:
  - build
  - test
  - docs
  - deploy

build:
  stage: build
  artifacts:
    untracked: true
  script:
    - curl -sL https://deb.nodesource.com/setup_current.x | bash -
    - apt-get install -y nodejs
    - cd CartaWeb/ClientApp/
    - npm ci --cache $HOME/.npm --prefer-offline
    - cd ../../
    - dotnet build --configuration Release

test:
  stage: test
  artifacts:
    paths:
      - coverage.lcov
  script:
    - dotnet test --configuration Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput='../coverage.lcov'

docs-coverage:
  stage: docs
  only:
    - master
  dependencies:
    - test
  artifacts:
    untracked: true
  script:
    - dotnet tool install -g dotnet-reportgenerator-globaltool
    - export PATH=$PATH:$HOME/.dotnet/tools
    - . ~/.bashrc
    - reportgenerator

# docs-projects:
#   stage: docs
#   only:
#     - master
#   dependencies:
#     - build
#   artifacts:
#     untracked: true
#   script:
#     - choco install docfx -y

pages:
  stage: deploy
  only:
    - master
  dependencies:
    - docs-coverage
  artifacts:
    paths:
      - public
  script:
    - mkdir public/
    - mv coverage/ public/coverage/
