default:
  image: mcr.microsoft.com/dotnet/sdk:5.0

cache:
  paths:
    - $HOME/.npm/

stages:
  - build
  - test
  - docs
  - deploy

build:
  stage: build
  script:
    - curl -sL https://deb.nodesource.com/setup_current.x | bash -
    - apt-get install -y nodejs
    - cd CartaWeb/ClientApp/
    - npm ci --cache $HOME/.npm --prefer-offline
    - cd ../../
    - dotnet build --configuration Release

publish:
  stage: build
  only:
    - tags
  artifacts:
    paths:
      - package.zip
  script:
    - curl -sL https://deb.nodesource.com/setup_current.x | bash -
    - apt-get install -y zip unzip
    - apt-get install -y nodejs
    - dotnet publish --configuration Release CartaWeb/ -o package
    - cd package
    - zip -r ../package.zip *

test:
  stage: test
  artifacts:
    paths:
      - coverage.lcov
  script:
    - >
      dotnet test --configuration Release
      /p:CollectCoverage=true
      /p:CoverletOutputFormat=lcov
      /p:CoverletOutput='../coverage.lcov'

docs-coverage:
  stage: docs
  only:
    - master
  dependencies:
    - test
  artifacts:
    untracked: true
  script:
    - dotnet tool install -g dotnet-reportgenerator-globaltool
    - export PATH=$PATH:$HOME/.dotnet/tools
    - . ~/.bashrc
    - reportgenerator

docs-projects:
  image: erothejoker/docker-docfx:latest
  stage: docs
  only:
    - master
  dependencies:
    - build
  artifacts:
    paths:
      - docfx_project/_site
  script:
    - docfx docfx_project/docfx.json

pages:
  stage: deploy
  only:
    - master
  dependencies:
    - docs-projects
    - docs-coverage
  artifacts:
    paths:
      - public
  script:
    - mv docfx_project/_site public/
    - mv coverage/ public/coverage/

deploy:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  only:
    - tags
  dependencies:
    - publish
  script:
    - aws s3 cp package.zip s3://$AWS_S3_BUCKET/package-$CI_COMMIT_TAG.zip
    - >
      aws elasticbeanstalk create-application-version
      --application-name Carta
      --version-label Carta-$CI_COMMIT_TAG
      --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key=package-$CI_COMMIT_TAG.zip
    - >
      aws elasticbeanstalk update-environment
      --application-name Carta
      --environment-name Carta-dev
      --version-label Carta-$CI_COMMIT_TAG
