default:
  image: mcr.microsoft.com/dotnet/sdk:3.1

before_script:
  - curl -sL https://deb.nodesource.com/setup_current.x | -E bash -
  - apt-get install -y nodejs

stages:
  - build
  - test

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  script:
    - dotnet test
