default:
  image: mcr.microsoft.com/dotnet/sdk:3.1

cache:
  paths:
    - $HOME/.npm/

stages:
  - build
  - test
  - docs
  - deploy

build:
  stage: build
  script:
    - curl -sL https://deb.nodesource.com/setup_current.x | bash -
    - apt-get install -y nodejs
    - cd CartaWeb/ClientApp/
    - npm ci --cache $HOME/.npm --prefer-offline
    - cd ../../
    - dotnet build

test:
  stage: test
  artifacts:
    untracked: true
  script:
    - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput='../coverage.lcov'

docs-coverage:
  stage: docs
  dependencies:
    - test
  artifacts:
    untracked: true
  script:
    - dotnet tool install -g dotnet-reportgenerator-globaltool
    - reportgenerator

pages:
  stage: deploy
  only:
    - master
  dependencies:
    - docs-coverage
  artifacts:
    paths:
      - public
  script:
    - mv coverage/ public/coverage/
